name: Build and push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 12 */15 * *' # Runs at 8:00 AM EST for every 2 weeks

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install semver
        run: npm install -g semver

      - name: Version File Creation
        run: |
          if [ ! -f VERSION ]; then
          echo "0.1.0" > VERSION
          fi
      - name: Version Bump
        id: version
        run: |
          CURRENT_VERSION=$(cat VERSION)
          NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          echo $NEW_VERSION > VERSION
          echo "::set-output name=version::$NEW_VERSION"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Bump version to $NEW_VERSION"
          git push

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deleting the Existing Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_TAG=latest
          docker pull $IMAGE_NAME:$IMAGE_TAG || true
          docker rmi $IMAGE_NAME:$IMAGE_TAG || true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}